Added docs, processing
alliance-genome/agr_blastdb_manager pull request #37
Opened 2024-02-08 21:23 UTC by nuin

S3/EFS features are on its branch

Added docs, comments, and checking for processed files (at least on the same day), which still needs some work

2024-02-08 21:55 UTC, adamjohnwright requested changes
Just the typo. The rest looks good

2024-02-08 21:55 UTC, adamjohnwright commented on src/utils.py
> +Author: Paulo Nuin, Adam Wrioght
Typo in my last name

2024-02-09 15:18 UTC, nuin commented on src/utils.py
> +Author: Paulo Nuin, Adam Wrioght
I blame AI

2024-02-09 20:46 UTC, adamjohnwright approved these changes

2024-02-09 20:47 UTC, merged